### ISSUE TITLE
代码运行crash

### ISSUE THREAD

**Issue by zchrissirhcz** [samylee/LazyNet#1]
你好，家兴！

感谢你的分享。我试着配置运行了你的LazyNet代码，由于不确定包含的openblas和opencv分别是32位还是64位的库，以及openblas版本也不确定，我换成了如下组合：
- vs2017, 64位编译
- opencv 3.4.9, 官网下载的预编译包
- openblas, 官网下载的0.3.9版本，自行基于cmake编译

配置好工程后，编译正确，运行出现了crash。不知你的代码后续有更新吗？

![image](https://user-images.githubusercontent.com/3831847/80860623-85278280-8c9b-11ea-9fff-6220ff83c26d.png)

补充一下：
- 我检查了读取图片的路径，改为了绝对路径；
- 我在Debug模式下运行，发现Flow类的构造函数(src/flow.cpp)缺少成员初始化，我从：
```c++
Flow::Flow() 
{
}
```
修改为：
```c++
Flow::Flow() : data_(nullptr), diff_(nullptr), number_(0), channel_(0), height_(0), width_(0)
{
}
```
此时运行推进了一步但仍然报错：
![image](https://user-images.githubusercontent.com/3831847/80860791-b5235580-8c9c-11ea-8d6a-c570dc3c480f.png)

**Comment by zchrissirhcz** [comment]
排查发现最新OpenBLAS在window下需要手动编译，讨论帖[在此处](https://github.com/xianyi/OpenBLAS/issues/2595)，能解决一个cblas_sgemm的crash问题。不过整份LazyNet的运行还是有问题。

**Comment by zchrissirhcz** [comment]
训练数据数量过少也会导致crash，改回原本设定即可。

**Comment by zchrissirhcz** [comment]
训练数据数量过少也会导致crash，改回原本设定即可。

**Comment by samylee** [comment]
@zchrissirhcz 你好，很久没有上github了，不好意思回复晚了，现在运行还有问题吗？

**Comment by zchrissirhcz** [comment]
按照我提到的几处修改后，可以训练，不会报错。
